spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: dummy

# Additional JPA properties
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true