spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.jzq95zp.mongodb.net/?retryWrites=true&w=majority
      database: testdb

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    jpa:
      hibernate:
       ddl-auto: update
      show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "caches"
      base-path: "/app-dashboard"
  endpoint:
      health:
        show-details: always


logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    com.learn.spring.spring: DEBUG